---
numbers:
  - '\d\.\d|\d'
space:
  - '\s'
keywords:
  - '\bBEGIN\b'
  - '\bEND\b'
  - '\b__ENCODING__\b'
  - '\b__END__\b'
  - '\b__FILE__\b'
  - '\b__LINE__\b'
  - '\balias\b'
  - '\bbegin\b'
  - '\bbreak\b'
  - '\bcase\b'
  - '\bclass\b'
  - '\bdef\b'
  - '\bdefined?\b'
  - '\bdo\b'
  - '\belse\b'
  - '\belsif\b'
  - '\bend\b'
  - '\bensure\b'
  - '\bfor\b'
  - '\bif\b'
  - '\bin\b'
  - '\bmodule\b'
  - '\bnext\b'
  - '\bredo\b'
  - '\brescue\b'
  - '\bretry\b'
  - '\breturn\b'
  - '\bself\b'
  - '\bsuper\b'
  - '\bthen\b'
  - '\bundef\b'
  - '\bunless\b'
  - '\buntil\b'
  - '\bwhen\b'
  - '\bwhile\b'
  - '\byield\b'
italian_keywords:  
  - '\bINIZIO\b'
  - '\bFINE\b'
  - '\b__CODIFICA__\b'
  - '\b__FINE__\b'
  - '\b__FILE__\b'
  - '\b__LINEA__\b'
  - '\balias\b'
  - '\binizio\b'
  - '\binterrompi\b'
  - '\bcontrolla\b'
  - '\bclasse\b'
  - '\bdefinisco\b'
  - '\bdefinito\?\b'
  - '\bfai\b'
  - '\baltrimenti\b'
  - '\baltrimenti_se\b'
  - '\bfine\b'
  - '\bgarantisci\b'
  - '\bper\b'
  - '\bse\b'
  - '\bdentro\b'
  - '\bmodulo\b'
  - '\bprossimo\b'
  - '\brifai\b'
  - '\bsoccorri\b'
  - '\briprova\b'
  - '\brestituisci\b'
  - '\bse_stesso\b'
  - '\bantenato\b'
  - '\bpoi\b'
  - '\brimuovi_definizione\b'
  - '\bsalvo_che\b'
  - '\bfino_a_che\b'
  - '\bmentre\b'
  - '\bwhile\b'
  - '\brendi\b'
  - '\bvero\b'
  - '\bfalso\b'
booleans:
  - 'true'
  - 'false'
strings:
  - '''\b\w+\b\'''
  - '"\b\w+\b"'
comments:
  - '#.*$'
  - '=begin\W.*\W=end'
symbols:
  - ':\b\w+\b'
  - ':''\b\w+\b'''
  - ':"\b\w+\b"'
variables:
  - '@\b\w+\b'
  - '@@\b\w+\b'
  - '\$\b\w+\b'
constants:
  - '\b[A-Z]+\b'
classes:
  - '\b[A-Z][a-z]+\b'
modules:
  - '\b[A-Z][a-z]+\b'
methods:
  - 'nil\?'
  - 'new'
parenthesis:
  - '('
  - ')'
  - '['
  - ']'
  - '{'
  - '}'
operators:
  - '+'
  - '-'
  - '*'
  - '\/'
  - '='
  - '!'
  - '~'
  - '%'
  - '<'
  - '>'
  - '$'
  - '&'
  - '|'
  - '?'
  - '^'
  - '.'
  - ':'
  - '\bor\b'
  - '\bnot\b'
  - '\band\b'
  - '\bnil\b'
punctuations:
  - ';'
  - ','
highlight0:
  - ''
highlight1:
  - ''
highlight2:
  - ''
highlight3:
  - ''
highlight4:
  - ''
highlight5:
  - ''
highlight6:
  - ''
highlight7:
  - ''
highlight8:
  - ''
highlight9:
  - ''

