---
preamble:
  - '#encoding: utf-8'
  - 'import javafx.scene.paint.Color'
  - 'import javafx.scene.shape.ArcType'
  - 'import javafx.scene.image.Image'
  - 'import javafx.scene.text.Font'
  - 'import javafx.scene.text.TextAlignment'
  - 'import javafx.geometry.VPos'
  - 'import javafx.geometry.HPos'
  - 'import javafx.scene.text.FontSmoothingType'
  - 'import javafx.scene.shape.StrokeLineCap'
  - 'import javafx.scene.shape.StrokeLineJoin'
  - 'import javafx.scene.shape.FillRule'

postamble:
  - ''

